nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.5.0.cjs

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: '@yarnpkg/plugin-interactive-tools'

enableGlobalCache: true

logFilters:
  - code: YN0013
    level: discard
